/* Auto-generated by generate_embedded_resources.ps1. Do not edit by hand. */
#include <windows.h>
#include "embedded_resources.h"

typedef struct EmbeddedResourceEntry
{
    const char *group;
    const char *name;
    const unsigned char *data;
    unsigned long size;
} EmbeddedResourceEntry;

static const EmbeddedResourceEntry g_embedded_resources[] =
{
    { NULL, NULL, NULL, 0 }
};
static const int g_embedded_resource_count = 0;

static int EmbeddedResources_ToLower(int c)
{
    if (c >= 'A' && c <= 'Z')
        return c + ('a' - 'A');

    return c;
}

static int EmbeddedResources_SameNoCase(const char *a, const char *b)
{
    int i;

    if (!a || !b)
        return 0;

    for (i = 0; a[i] || b[i]; i++)
    {
        if (EmbeddedResources_ToLower((unsigned char)a[i]) != EmbeddedResources_ToLower((unsigned char)b[i]))
            return 0;
    }

    return 1;
}

static void EmbeddedResources_NormalizeName(const char *src, char *dest, int destSize)
{
    int i;

    if (!dest || destSize <= 0)
        return;

    dest[0] = '\0';

    if (!src)
        return;

    for (i = 0; src[i] && i < destSize - 1; i++)
    {
        if (src[i] == '\\')
            dest[i] = '/';
        else
            dest[i] = src[i];
    }

    dest[i] = '\0';
}

static const char *EmbeddedResources_BaseName(const char *name)
{
    const char *base;
    int i;

    if (!name)
        return "";

    base = name;

    for (i = 0; name[i]; i++)
    {
        if (name[i] == '/' || name[i] == '\\')
            base = name + i + 1;
    }

    return base;
}

int EmbeddedResources_Find(
    const char *group,
    const char *name,
    const unsigned char **data,
    unsigned long *size
)
{
    char normalized[512];
    const char *base;
    int i;

    if (data)
        *data = NULL;

    if (size)
        *size = 0;

    if (!group || !name || !data || !size)
        return 0;

    EmbeddedResources_NormalizeName(name, normalized, sizeof(normalized));
    base = EmbeddedResources_BaseName(normalized);

    for (i = 0; i < g_embedded_resource_count; i++)
    {
        if (!EmbeddedResources_SameNoCase(g_embedded_resources[i].group, group))
            continue;

        if (EmbeddedResources_SameNoCase(g_embedded_resources[i].name, normalized))
        {
            *data = g_embedded_resources[i].data;
            *size = g_embedded_resources[i].size;
            return 1;
        }
    }

    for (i = 0; i < g_embedded_resource_count; i++)
    {
        if (!EmbeddedResources_SameNoCase(g_embedded_resources[i].group, group))
            continue;

        if (EmbeddedResources_SameNoCase(EmbeddedResources_BaseName(g_embedded_resources[i].name), base))
        {
            *data = g_embedded_resources[i].data;
            *size = g_embedded_resources[i].size;
            return 1;
        }
    }

    return 0;
}
