param(
    [string]$Root = ".",
    [string]$OutFile = "ini_resources_generated.c"
)

$ErrorActionPreference = "Stop"

function Test-SkippedPath {
    param([string]$RelativePath)

    $parts = $RelativePath -split '[\\/]'

    foreach ($part in $parts) {
        if ($part -like "build_*") { return $true }
        if ($part -like "source_*") { return $true }
        if ($part -ieq "oldbuilds") { return $true }
        if ($part -ieq "temp") { return $true }
    }

    return $false
}

function Convert-ToCString {
    param([string]$Text)

    return $Text.Replace("\", "\\").Replace('"', '\"')
}

$rootPath = (Resolve-Path $Root).Path

$files = @()

if (Test-Path $rootPath) {
    $files =
        Get-ChildItem -Path $rootPath -Filter "*.ini" -File -Recurse |
        Sort-Object FullName |
        ForEach-Object {
            $relative = $_.FullName.Substring($rootPath.Length).TrimStart('\', '/').Replace('\', '/')

            if (-not (Test-SkippedPath $relative)) {
                [PSCustomObject]@{
                    FullName = $_.FullName
                    Relative = $relative
                }
            }
        }
}

$writer = New-Object System.IO.StreamWriter($OutFile, $false, [System.Text.Encoding]::ASCII)

try {
    $writer.WriteLine("/* Auto-generated by generate_ini_resources.ps1. Do not edit by hand. */")
    $writer.WriteLine("#include <windows.h>")
    $writer.WriteLine('#include "ini_resources.h"')
    $writer.WriteLine("")

    $index = 0

    foreach ($file in $files) {
        $bytes = [System.IO.File]::ReadAllBytes($file.FullName)

        $writer.WriteLine("static const unsigned char g_ini_resource_data_$index[] =")
        $writer.WriteLine("{")

        if ($bytes.Length -eq 0) {
            $writer.WriteLine("    0x00")
        }
        else {
            for ($i = 0; $i -lt $bytes.Length; $i += 12) {
                $chunk = $bytes[$i..([Math]::Min($i + 11, $bytes.Length - 1))]
                $line = ($chunk | ForEach-Object { ("0x{0:X2}" -f $_) }) -join ", "

                if ($i + 12 -lt $bytes.Length) {
                    $writer.WriteLine("    $line,")
                }
                else {
                    $writer.WriteLine("    $line")
                }
            }
        }

        $writer.WriteLine("};")
        $writer.WriteLine("static const unsigned long g_ini_resource_size_$index = $($bytes.Length)UL;")
        $writer.WriteLine("")

        $index++
    }

    $writer.WriteLine("typedef struct IniResourceEntry")
    $writer.WriteLine("{")
    $writer.WriteLine("    const char *name;")
    $writer.WriteLine("    const unsigned char *data;")
    $writer.WriteLine("    unsigned long size;")
    $writer.WriteLine("} IniResourceEntry;")
    $writer.WriteLine("")

    if ($files.Count -gt 0) {
        $writer.WriteLine("static const IniResourceEntry g_ini_resources[] =")
        $writer.WriteLine("{")

        for ($i = 0; $i -lt $files.Count; $i++) {
            $name = Convert-ToCString $files[$i].Relative
            $writer.WriteLine("    { `"$name`", g_ini_resource_data_$i, g_ini_resource_size_$i },")
        }

        $writer.WriteLine("};")
        $writer.WriteLine("static const int g_ini_resource_count = $($files.Count);")
    }
    else {
        $writer.WriteLine("static const IniResourceEntry g_ini_resources[] =")
        $writer.WriteLine("{")
        $writer.WriteLine("    { NULL, NULL, 0 }")
        $writer.WriteLine("};")
        $writer.WriteLine("static const int g_ini_resource_count = 0;")
    }

    $writer.WriteLine("")
    $writer.WriteLine("static int IniResources_ToLower(int c)")
    $writer.WriteLine("{")
    $writer.WriteLine("    if (c >= 'A' && c <= 'Z')")
    $writer.WriteLine("        return c + ('a' - 'A');")
    $writer.WriteLine("")
    $writer.WriteLine("    return c;")
    $writer.WriteLine("}")
    $writer.WriteLine("")
    $writer.WriteLine("static int IniResources_SameNoCase(const char *a, const char *b)")
    $writer.WriteLine("{")
    $writer.WriteLine("    int i;")
    $writer.WriteLine("")
    $writer.WriteLine("    if (!a || !b)")
    $writer.WriteLine("        return 0;")
    $writer.WriteLine("")
    $writer.WriteLine("    for (i = 0; a[i] || b[i]; i++)")
    $writer.WriteLine("    {")
    $writer.WriteLine("        if (IniResources_ToLower((unsigned char)a[i]) != IniResources_ToLower((unsigned char)b[i]))")
    $writer.WriteLine("            return 0;")
    $writer.WriteLine("    }")
    $writer.WriteLine("")
    $writer.WriteLine("    return 1;")
    $writer.WriteLine("}")
    $writer.WriteLine("")
    $writer.WriteLine("static void IniResources_NormalizeName(const char *src, char *dest, int destSize)")
    $writer.WriteLine("{")
    $writer.WriteLine("    int i;")
    $writer.WriteLine("")
    $writer.WriteLine("    if (!dest || destSize <= 0)")
    $writer.WriteLine("        return;")
    $writer.WriteLine("")
    $writer.WriteLine("    dest[0] = '\0';")
    $writer.WriteLine("")
    $writer.WriteLine("    if (!src)")
    $writer.WriteLine("        return;")
    $writer.WriteLine("")
    $writer.WriteLine("    for (i = 0; src[i] && i < destSize - 1; i++)")
    $writer.WriteLine("    {")
    $writer.WriteLine("        if (src[i] == '\\')")
    $writer.WriteLine("            dest[i] = '/';")
    $writer.WriteLine("        else")
    $writer.WriteLine("            dest[i] = src[i];")
    $writer.WriteLine("    }")
    $writer.WriteLine("")
    $writer.WriteLine("    dest[i] = '\0';")
    $writer.WriteLine("}")
    $writer.WriteLine("")
    $writer.WriteLine("static const char *IniResources_BaseName(const char *name)")
    $writer.WriteLine("{")
    $writer.WriteLine("    const char *base;")
    $writer.WriteLine("    int i;")
    $writer.WriteLine("")
    $writer.WriteLine("    if (!name)")
    $writer.WriteLine("        return \"\";")
    $writer.WriteLine("")
    $writer.WriteLine("    base = name;")
    $writer.WriteLine("")
    $writer.WriteLine("    for (i = 0; name[i]; i++)")
    $writer.WriteLine("    {")
    $writer.WriteLine("        if (name[i] == '/' || name[i] == '\\')")
    $writer.WriteLine("            base = name + i + 1;")
    $writer.WriteLine("    }")
    $writer.WriteLine("")
    $writer.WriteLine("    return base;")
    $writer.WriteLine("}")
    $writer.WriteLine("")
    $writer.WriteLine("int IniResources_Find(")
    $writer.WriteLine("    const char *name,")
    $writer.WriteLine("    const unsigned char **data,")
    $writer.WriteLine("    unsigned long *size")
 base;")
    $writer.WriteLine("}")
    $writer.WriteLine("")
    $writer.WriteLine("int IniResources_Find("    $writer.WriteLine(")")
    $writer.WriteLine("{")
    $writer.WriteLine("    char normalized[512];")
    $writer.WriteLine("    const char *base;")
    $writer.WriteLine("    int i;")
    $writer.WriteLine("")
    $writer.WriteLine("    if (data)")
    $writer.WriteLine("        *data = NULL;")
    $writer.WriteLine("")
    $writer.WriteLine("    if (size)")
    $writer.WriteLine("        *size = 0;")
    $writer.WriteLine("")
    $writer.WriteLine("    if (!name || !data || !size)")
    $writer.WriteLine("        return 0;")
    $writer.WriteLine("")
    $writer.WriteLine("    IniResources_NormalizeName(name, normalized, sizeof(normalized));")
    $writer.WriteLine("    base = IniResources_BaseName(normalized);")
    $writer.WriteLine("")
    $writer.WriteLine("    for (i = 0; i < g_ini_resource_count; i++)")
    $writer.WriteLine("    {")
    $writer.WriteLine("        if (IniResources_SameNoCase(g_ini_resources[i].name, normalized))")
    $writer.WriteLine("        {")
    $writer.WriteLine("            *data = g_ini_resources[i].data;")
    $writer.WriteLine("            *size = g_ini_resources[i].size;")
    $writer.WriteLine("            return 1;")
    $writer.WriteLine("        }")
    $writer.WriteLine("    }")
    $writer.WriteLine("")
    $writer.WriteLine("    for (i = 0; i < g_ini_resource_count; i++)")
    $writer.WriteLine("    {")
    $writer.WriteLine("        if (IniResources_SameNoCase(IniResources_BaseName(g_ini_resources[i].name), base))")
    $writer.WriteLine("        {")
    $writer.WriteLine("            *data = g_ini_resources[i].data;")
    $writer.WriteLine("            *size = g_ini_resources[i].size;")
    $writer.WriteLine("            return 1;")
    $writer.WriteLine("        }")
    $writer.WriteLine("    }")
    $writer.WriteLine("")
    $writer.WriteLine("    return 0;")
    $writer.WriteLine("}")
}
finally {
    $writer.Close()
}

Write-Host "Generated $OutFile with $($files.Count) embedded INI file(s)."