param(
    [string]$Root = ".",
    [string]$OutFile = "embedded_resources_generated.c",
    [string]$Group = "ini",
    [string[]]$Include = @("*.ini")
)

$ErrorActionPreference = "Stop"

function Test-SkippedPath {
    param([string]$RelativePath)

    $parts = $RelativePath -split '[\\/]'

    foreach ($part in $parts) {
        if ($part -like "build_*") { return $true }
        if ($part -like "source_*") { return $true }
        if ($part -ieq "oldbuilds") { return $true }
        if ($part -ieq "temp") { return $true }
    }

    return $false
}

function Test-IncludedFile {
    param([string]$Name)

    foreach ($pattern in $Include) {
        if ($Name -like $pattern) {
            return $true
        }
    }

    return $false
}

function Convert-ToCString {
    param([string]$Text)

    return $Text.Replace('\', '\\').Replace('"', '\"')
}

$rootPath = (Resolve-Path $Root).Path

$files = @()

if (Test-Path $rootPath) {
    $files =
        Get-ChildItem -Path $rootPath -File -Recurse |
        Sort-Object FullName |
        ForEach-Object {
            $relative = $_.FullName.Substring($rootPath.Length).TrimStart('\', '/').Replace('\', '/')

            if ((Test-IncludedFile $_.Name) -and (-not (Test-SkippedPath $relative))) {
                [PSCustomObject]@{
                    FullName = $_.FullName
                    Relative = $relative
                }
            }
        }
}

$writer = New-Object System.IO.StreamWriter($OutFile, $false, [System.Text.Encoding]::ASCII)

try {
    $writer.WriteLine('/* Auto-generated by generate_embedded_resources.ps1. Do not edit by hand. */')
    $writer.WriteLine('#include <windows.h>')
    $writer.WriteLine('#include "embedded_resources.h"')
    $writer.WriteLine('')

    for ($index = 0; $index -lt $files.Count; $index++) {
        $bytes = [System.IO.File]::ReadAllBytes($files[$index].FullName)

        $writer.WriteLine("static const unsigned char g_embedded_resource_data_$index[] =")
        $writer.WriteLine('{')

        if ($bytes.Length -eq 0) {
            $writer.WriteLine('    0x00')
        }
        else {
            for ($i = 0; $i -lt $bytes.Length; $i += 12) {
                $end = [Math]::Min($i + 11, $bytes.Length - 1)
                $chunk = $bytes[$i..$end]
                $line = ($chunk | ForEach-Object { ('0x{0:X2}' -f $_) }) -join ', '

                if ($end -lt $bytes.Length - 1) {
                    $writer.WriteLine("    $line,")
                }
                else {
                    $writer.WriteLine("    $line")
                }
            }
        }

        $writer.WriteLine('};')
        $writer.WriteLine('')
    }

    $writer.WriteLine('typedef struct EmbeddedResourceEntry')
    $writer.WriteLine('{')
    $writer.WriteLine('    const char *group;')
    $writer.WriteLine('    const char *name;')
    $writer.WriteLine('    const unsigned char *data;')
    $writer.WriteLine('    unsigned long size;')
    $writer.WriteLine('} EmbeddedResourceEntry;')
    $writer.WriteLine('')

    if ($files.Count -gt 0) {
        $writer.WriteLine('static const EmbeddedResourceEntry g_embedded_resources[] =')
        $writer.WriteLine('{')

        for ($i = 0; $i -lt $files.Count; $i++) {
            $name = Convert-ToCString $files[$i].Relative
            $groupName = Convert-ToCString $Group
            $sizeLiteral = ([System.IO.FileInfo]$files[$i].FullName).Length

            $writer.WriteLine("    { `"$groupName`", `"$name`", g_embedded_resource_data_$i, $($sizeLiteral)UL },")
        }

        $writer.WriteLine('};')
        $writer.WriteLine("static const int g_embedded_resource_count = $($files.Count);")
    }
    else {
        $writer.WriteLine('static const EmbeddedResourceEntry g_embedded_resources[] =')
        $writer.WriteLine('{')
        $writer.WriteLine('    { NULL, NULL, NULL, 0UL }')
        $writer.WriteLine('};')
        $writer.WriteLine('static const int g_embedded_resource_count = 0;')
    }

    $writer.WriteLine('')
    $writer.WriteLine('static int EmbeddedResources_ToLower(int c)')
    $writer.WriteLine('{')
    $writer.WriteLine("    if (c >= 'A' && c <= 'Z')")
    $writer.WriteLine("        return c + ('a' - 'A');")
    $writer.WriteLine('')
    $writer.WriteLine('    return c;')
    $writer.WriteLine('}')
    $writer.WriteLine('')
    $writer.WriteLine('static int EmbeddedResources_SameNoCase(const char *a, const char *b)')
    $writer.WriteLine('{')
    $writer.WriteLine('    int i;')
    $writer.WriteLine('')
    $writer.WriteLine('    if (!a || !b)')
    $writer.WriteLine('        return 0;')
    $writer.WriteLine('')
    $writer.WriteLine('    for (i = 0; a[i] || b[i]; i++)')
    $writer.WriteLine('    {')
    $writer.WriteLine('        if (EmbeddedResources_ToLower((unsigned char)a[i]) != EmbeddedResources_ToLower((unsigned char)b[i]))')
    $writer.WriteLine('            return 0;')
    $writer.WriteLine('    }')
    $writer.WriteLine('')
    $writer.WriteLine('    return 1;')
    $writer.WriteLine('}')
    $writer.WriteLine('')
    $writer.WriteLine('static void EmbeddedResources_NormalizeName(const char *src, char *dest, int destSize)')
    $writer.WriteLine('{')
    $writer.WriteLine('    int i;')
    $writer.WriteLine('')
    $writer.WriteLine('    if (!dest || destSize <= 0)')
    $writer.WriteLine('        return;')
    $writer.WriteLine('')
    $writer.WriteLine("    dest[0] = '\0';")
    $writer.WriteLine('')
    $writer.WriteLine('    if (!src)')
    $writer.WriteLine('        return;')
    $writer.WriteLine('')
    $writer.WriteLine('    for (i = 0; src[i] && i < destSize - 1; i++)')
    $writer.WriteLine('    {')
    $writer.WriteLine("        if (src[i] == '\\')")
    $writer.WriteLine("            dest[i] = '/';")
    $writer.WriteLine('        else')
    $writer.WriteLine('            dest[i] = src[i];')
    $writer.WriteLine('    }')
    $writer.WriteLine('')
    $writer.WriteLine("    dest[i] = '\0';")
    $writer.WriteLine('}')
    $writer.WriteLine('')
    $writer.WriteLine('static const char *EmbeddedResources_BaseName(const char *name)')
    $writer.WriteLine('{')
    $writer.WriteLine('    const char *base;')
    $writer.WriteLine('    int i;')
    $writer.WriteLine('')
    $writer.WriteLine('    if (!name)')
    $writer.WriteLine('        return "";')
    $writer.WriteLine('')
    $writer.WriteLine('    base = name;')
    $writer.WriteLine('')
    $writer.WriteLine('    for (i = 0; name[i]; i++)')
    $writer.WriteLine('    {')
    $writer.WriteLine("        if (name[i] == '/' || name[i] == '\\')")
    $writer.WriteLine('            base = name + i + 1;')
    $writer.WriteLine('    }')
    $writer.WriteLine('')
    $writer.WriteLine('    return base;')
    $writer.WriteLine('}')
    $writer.WriteLine('')
    $writer.WriteLine('int EmbeddedResources_Find(')
    $writer.WriteLine('    const char *group,')
    $writer.WriteLine('    const char *name,')
    $writer.WriteLine('    const unsigned char **data,')
    $writer.WriteLine('    unsigned long *size')
    $writer.WriteLine(')')
    $writer.WriteLine('{')
    $writer.WriteLine('    char normalized[512];')
    $writer.WriteLine('    const char *base;')
    $writer.WriteLine('    int i;')
    $writer.WriteLine('')
    $writer.WriteLine('    if (data)')
    $writer.WriteLine('        *data = NULL;')
    $writer.WriteLine('')
    $writer.WriteLine('    if (size)')
    $writer.WriteLine('        *size = 0;')
    $writer.WriteLine('')
    $writer.WriteLine('    if (!group || !name || !data || !size)')
    $writer.WriteLine('        return 0;')
    $writer.WriteLine('')
    $writer.WriteLine('    EmbeddedResources_NormalizeName(name, normalized, sizeof(normalized));')
    $writer.WriteLine('    base = EmbeddedResources_BaseName(normalized);')
    $writer.WriteLine('')
    $writer.WriteLine('    for (i = 0; i < g_embedded_resource_count; i++)')
    $writer.WriteLine('    {')
    $writer.WriteLine('        if (!EmbeddedResources_SameNoCase(g_embedded_resources[i].group, group))')
    $writer.WriteLine('            continue;')
    $writer.WriteLine('')
    $writer.WriteLine('        if (EmbeddedResources_SameNoCase(g_embedded_resources[i].name, normalized))')
    $writer.WriteLine('        {')
    $writer.WriteLine('            *data = g_embedded_resources[i].data;')
    $writer.WriteLine('            *size = g_embedded_resources[i].size;')
    $writer.WriteLine('            return 1;')
    $writer.WriteLine('        }')
    $writer.WriteLine('    }')
    $writer.WriteLine('')
    $writer.WriteLine('    for (i = 0; i < g_embedded_resource_count; i++)')
    $writer.WriteLine('    {')
    $writer.WriteLine('        if (!EmbeddedResources_SameNoCase(g_embedded_resources[i].group, group))')
    $writer.WriteLine('            continue;')
    $writer.WriteLine('')
    $writer.WriteLine('        if (EmbeddedResources_SameNoCase(EmbeddedResources_BaseName(g_embedded_resources[i].name), base))')
    $writer.WriteLine('        {')
    $writer.WriteLine('            *data = g_embedded_resources[i].data;')
    $writer.WriteLine('            *size = g_embedded_resources[i].size;')
    $writer.WriteLine('            return 1;')
    $writer.WriteLine('        }')
    $writer.WriteLine('    }')
    $writer.WriteLine('')
    $writer.WriteLine('    return 0;')
    $writer.WriteLine('}')
}
finally {
    $writer.Close()
}

Write-Host "Generated $OutFile with $($files.Count) embedded resource file(s) in group '$Group'."